using static JT.Extension.JTEnumExt;
namespace JT.GDal.Standards {
    public enum GdalDriverNames {
        [JTEnumStringAttribute("VRT")]
        VRT,
        [JTEnumStringAttribute("GTiff")]
        GTiff,
        [JTEnumStringAttribute("NITF")]
        NITF,
        [JTEnumStringAttribute("RPFTOC")]
        RPFTOC,
        [JTEnumStringAttribute("ECRGTOC")]
        ECRGTOC,
        [JTEnumStringAttribute("HFA")]
        HFA,
        [JTEnumStringAttribute("SAR_CEOS")]
        SAR_CEOS,
        [JTEnumStringAttribute("CEOS")]
        CEOS,
        [JTEnumStringAttribute("JAXAPALSAR")]
        JAXAPALSAR,
        [JTEnumStringAttribute("GFF")]
        GFF,
        [JTEnumStringAttribute("ELAS")]
        ELAS,
        [JTEnumStringAttribute("AIG")]
        AIG,
        [JTEnumStringAttribute("AAIGrid")]
        AAIGrid,
        [JTEnumStringAttribute("GRASSASCIIGrid")]
        GRASSASCIIGrid,
        [JTEnumStringAttribute("SDTS")]
        SDTS,
        [JTEnumStringAttribute("DTED")]
        DTED,
        [JTEnumStringAttribute("PNG")]
        PNG,
        [JTEnumStringAttribute("JPEG")]
        JPEG,
        [JTEnumStringAttribute("MEM")]
        MEM,
        [JTEnumStringAttribute("JDEM")]
        JDEM,
        [JTEnumStringAttribute("GIF")]
        GIF,
        [JTEnumStringAttribute("BIGGIF")]
        BIGGIF,
        [JTEnumStringAttribute("ESAT")]
        ESAT,
        [JTEnumStringAttribute("BSB")]
        BSB,
        [JTEnumStringAttribute("XPM")]
        XPM,
        [JTEnumStringAttribute("BMP")]
        BMP,
        [JTEnumStringAttribute("DIMAP")]
        DIMAP,
        [JTEnumStringAttribute("AirSAR")]
        AirSAR,
        [JTEnumStringAttribute("RS2")]
        RS2,
        [JTEnumStringAttribute("PCIDSK")]
        PCIDSK,
        [JTEnumStringAttribute("PCRaster")]
        PCRaster,
        [JTEnumStringAttribute("ILWIS")]
        ILWIS,
        [JTEnumStringAttribute("SGI")]
        SGI,
        [JTEnumStringAttribute("SRTMHGT")]
        SRTMHGT,
        [JTEnumStringAttribute("Leveller")]
        Leveller,
        [JTEnumStringAttribute("Terragen")]
        Terragen,
        [JTEnumStringAttribute("ISIS3")]
        ISIS3,
        [JTEnumStringAttribute("ISIS2")]
        ISIS2,
        [JTEnumStringAttribute("PDS")]
        PDS,
        [JTEnumStringAttribute("TIL")]
        TIL,
        [JTEnumStringAttribute("ERS")]
        ERS,
        [JTEnumStringAttribute("JP2OpenJPEG")]
        JP2OpenJPEG,
        [JTEnumStringAttribute("L1B")]
        L1B,
        [JTEnumStringAttribute("FIT")]
        FIT,
        [JTEnumStringAttribute("GRIB")]
        GRIB,
        [JTEnumStringAttribute("RMF")]
        RMF,
        [JTEnumStringAttribute("WCS")]
        WCS,
        [JTEnumStringAttribute("WMS")]
        WMS,
        [JTEnumStringAttribute("MSGN")]
        MSGN,
        [JTEnumStringAttribute("RST")]
        RST,
        [JTEnumStringAttribute("INGR")]
        INGR,
        [JTEnumStringAttribute("GSAG")]
        GSAG,
        [JTEnumStringAttribute("GSBG")]
        GSBG,
        [JTEnumStringAttribute("GS7BG")]
        GS7BG,
        [JTEnumStringAttribute("COSAR")]
        COSAR,
        [JTEnumStringAttribute("TSX")]
        TSX,
        [JTEnumStringAttribute("COASP")]
        COASP,
        [JTEnumStringAttribute("R")]
        R,
        [JTEnumStringAttribute("MAP")]
        MAP,
        [JTEnumStringAttribute("PNM")]
        PNM,
        [JTEnumStringAttribute("DOQ1")]
        DOQ1,
        [JTEnumStringAttribute("DOQ2")]
        DOQ2,
        [JTEnumStringAttribute("ENVI")]
        ENVI,
        [JTEnumStringAttribute("EHdr")]
        EHdr,
        [JTEnumStringAttribute("GenBin")]
        GenBin,
        [JTEnumStringAttribute("PAux")]
        PAux,
        [JTEnumStringAttribute("MFF")]
        MFF,
        [JTEnumStringAttribute("MFF2")]
        MFF2,
        [JTEnumStringAttribute("FujiBAS")]
        FujiBAS,
        [JTEnumStringAttribute("GSC")]
        GSC,
        [JTEnumStringAttribute("FAST")]
        FAST,
        [JTEnumStringAttribute("BT")]
        BT,
        [JTEnumStringAttribute("LAN")]
        LAN,
        [JTEnumStringAttribute("CPG")]
        CPG,
        [JTEnumStringAttribute("IDA")]
        IDA,
        [JTEnumStringAttribute("NDF")]
        NDF,
        [JTEnumStringAttribute("EIR")]
        EIR,
        [JTEnumStringAttribute("DIPEx")]
        DIPEx,
        [JTEnumStringAttribute("LCP")]
        LCP,
        [JTEnumStringAttribute("GTX")]
        GTX,
        [JTEnumStringAttribute("LOSLAS")]
        LOSLAS,
        [JTEnumStringAttribute("NTv2")]
        NTv2,
        [JTEnumStringAttribute("CTable2")]
        CTable2,
        [JTEnumStringAttribute("ACE2")]
        ACE2,
        [JTEnumStringAttribute("SNODAS")]
        SNODAS,
        [JTEnumStringAttribute("KRO")]
        KRO,
        [JTEnumStringAttribute("ARG")]
        ARG,
        [JTEnumStringAttribute("RIK")]
        RIK,
        [JTEnumStringAttribute("USGSDEM")]
        USGSDEM,
        [JTEnumStringAttribute("GXF")]
        GXF,
        [JTEnumStringAttribute("HTTP")]
        HTTP,
        [JTEnumStringAttribute("NWT_GRD")]
        NWT_GRD,
        [JTEnumStringAttribute("NWT_GRC")]
        NWT_GRC,
        [JTEnumStringAttribute("ADRG")]
        ADRG,
        [JTEnumStringAttribute("SRP")]
        SRP,
        [JTEnumStringAttribute("BLX")]
        BLX,
        [JTEnumStringAttribute("Rasterlite")]
        Rasterlite,
        [JTEnumStringAttribute("PostGISRaster")]
        PostGISRaster,
        [JTEnumStringAttribute("SAGA")]
        SAGA,
        [JTEnumStringAttribute("KMLSUPEROVERLAY")]
        KMLSUPEROVERLAY,
        [JTEnumStringAttribute("XYZ")]
        XYZ,
        [JTEnumStringAttribute("HF2")]
        HF2,
        [JTEnumStringAttribute("PDF")]
        PDF,
        [JTEnumStringAttribute("OZI")]
        OZI,
        [JTEnumStringAttribute("CTG")]
        CTG,
        [JTEnumStringAttribute("E00GRID")]
        E00GRID,
        [JTEnumStringAttribute("ZMap")]
        ZMap,
        [JTEnumStringAttribute("NGSGEOID")]
        NGSGEOID,
        [JTEnumStringAttribute("MBTiles")]
        MBTiles,
        [JTEnumStringAttribute("IRIS")]
        IRIS,
    }
}