using static JT.Extension.JTEnumExt;
namespace JT.GDal.Standards {
    public enum OgrDriverNames {
        [JTEnumStringAttribute("ESRI Shapefile")]
        ESRIShapefile,
        [JTEnumStringAttribute("MapInfo File")]
        MapInfoFile,
        [JTEnumStringAttribute("UK .NTF")]
        UK_NTF,
        [JTEnumStringAttribute("SDTS")]
        SDTS,
        [JTEnumStringAttribute("TIGER")]
        TIGER,
        [JTEnumStringAttribute("S57")]
        S57,
        [JTEnumStringAttribute("DGN")]
        DGN,
        [JTEnumStringAttribute("VRT")]
        VRT,
        [JTEnumStringAttribute("REC")]
        REC,
        [JTEnumStringAttribute("Memory")]
        Memory,
        [JTEnumStringAttribute("BNA")]
        BNA,
        [JTEnumStringAttribute("CSV")]
        CSV,
        [JTEnumStringAttribute("NAS")]
        NAS,
        [JTEnumStringAttribute("GML")]
        GML,
        [JTEnumStringAttribute("GPX")]
        GPX,
        [JTEnumStringAttribute("LIBKML")]
        LIBKML,
        [JTEnumStringAttribute("KML")]
        KML,
        [JTEnumStringAttribute("GeoJSON")]
        GeoJSON,
        [JTEnumStringAttribute("Interlis 1")]
        Interlis1,
        [JTEnumStringAttribute("Interlis 2")]
        Interlis2,
        [JTEnumStringAttribute("GMT")]
        GMT,
        [JTEnumStringAttribute("GPKG")]
        GPKG,
        [JTEnumStringAttribute("SQLite")]
        SQLite,
        [JTEnumStringAttribute("ODBC")]
        ODBC,
        [JTEnumStringAttribute("WAsP")]
        WAsP,
        [JTEnumStringAttribute("PGeo")]
        PGeo,
        [JTEnumStringAttribute("MSSQLSpatial")]
        MSSQLSpatial,
        [JTEnumStringAttribute("PostgreSQL")]
        PostgreSQL,
        [JTEnumStringAttribute("MySQL")]
        MySQL,
        [JTEnumStringAttribute("PCIDSK")]
        PCIDSK,
        [JTEnumStringAttribute("OpenFileGDB")]
        OpenFileGDB,
        [JTEnumStringAttribute("XPlane")]
        XPlane,
        [JTEnumStringAttribute("AVCBin")]
        AVCBin,
        [JTEnumStringAttribute("AVCE00")]
        AVCE00,
        [JTEnumStringAttribute("DXF")]
        DXF,
        [JTEnumStringAttribute("Geoconcept")]
        Geoconcept,
        [JTEnumStringAttribute("GeoRSS")]
        GeoRSS,
        [JTEnumStringAttribute("GPSTrackMaker")]
        GPSTrackMaker,
        [JTEnumStringAttribute("VFK")]
        VFK,
        [JTEnumStringAttribute("PGDump")]
        PGDump,
        [JTEnumStringAttribute("OSM")]
        OSM,
        [JTEnumStringAttribute("GPSBabel")]
        GPSBabel,
        [JTEnumStringAttribute("SUA")]
        SUA,
        [JTEnumStringAttribute("OpenAir")]
        OpenAir,
        [JTEnumStringAttribute("PDS")]
        PDS,
        [JTEnumStringAttribute("WFS")]
        WFS,
        [JTEnumStringAttribute("HTF")]
        HTF,
        [JTEnumStringAttribute("AeronavFAA")]
        AeronavFAA,
        [JTEnumStringAttribute("Geomedia")]
        Geomedia,
        [JTEnumStringAttribute("EDIGEO")]
        EDIGEO,
        [JTEnumStringAttribute("GFT")]
        GFT,
        [JTEnumStringAttribute("GME")]
        GME,
        [JTEnumStringAttribute("SVG")]
        SVG,
        [JTEnumStringAttribute("CouchDB")]
        CouchDB,
        [JTEnumStringAttribute("Idrisi")]
        Idrisi,
        [JTEnumStringAttribute("ARCGEN")]
        ARCGEN,
        [JTEnumStringAttribute("SEGUKOOA")]
        SEGUKOOA,
        [JTEnumStringAttribute("SEGY")]
        SEGY,
        [JTEnumStringAttribute("ODS")]
        ODS,
        [JTEnumStringAttribute("XLSX")]
        XLSX,
        [JTEnumStringAttribute("ElasticSearch")]
        ElasticSearch,
        [JTEnumStringAttribute("PDF")]
        PDF,
        [JTEnumStringAttribute("Walk")]
        Walk,
        [JTEnumStringAttribute("CartoDB")]
        CartoDB,
        [JTEnumStringAttribute("SXF")]
        SXF,
    }
}