using static JT.Extension.JTEnumExt;
namespace JT.GDal.Standards {
    public enum WellKnownTextType {
        [JTEnumStringAttribute("Geometry")]
        Geometry,
        [JTEnumStringAttribute("Point")]
        Point,
        [JTEnumStringAttribute("LineString")]
        LineString,
        [JTEnumStringAttribute("Polygon")]
        Polygon,
        [JTEnumStringAttribute("MultiPoint")]
        MultiPoint,
        [JTEnumStringAttribute("MultiLineString")]
        MultiLineString,
        [JTEnumStringAttribute("MultiPolygon")]
        MultiPolygon,
        [JTEnumStringAttribute("GeometryCollection")]
        GeometryCollection,
        [JTEnumStringAttribute("CircularString")]
        CircularString,
        [JTEnumStringAttribute("CompoundCurve")]
        CompoundCurve,
        [JTEnumStringAttribute("CurvePolygon")]
        CurvePolygon,
        [JTEnumStringAttribute("MultiCurve")]
        MultiCurve,
        [JTEnumStringAttribute("MultiSurface")]
        MultiSurface,
        [JTEnumStringAttribute("Curve")]
        Curve,
        [JTEnumStringAttribute("Surface")]
        Surface,
        [JTEnumStringAttribute("PolyhedralSurface")]
        PolyhedralSurface,
        [JTEnumStringAttribute("TIN")]
        TIN,
        [JTEnumStringAttribute("Triangle")]
        Triangle,
        [JTEnumStringAttribute("Circle")]
        Circle,
        [JTEnumStringAttribute("GeodesicString")]
        GeodesicString,
        [JTEnumStringAttribute("EllipticalCurve")]
        EllipticalCurve,
        [JTEnumStringAttribute("NurbsCurve")]
        NurbsCurve,
        [JTEnumStringAttribute("Clothoid")]
        Clothoid,
        [JTEnumStringAttribute("SpiralCurve")]
        SpiralCurve,
        [JTEnumStringAttribute("CompoundSurface")]
        CompoundSurface,
        [JTEnumStringAttribute("BrepSolid")]
        BrepSolid,
        [JTEnumStringAttribute("AffinePlacement")]
        AffinePlacement,
    }
}
